on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'                # set this to the node version to use

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - 'latest'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ matrix.hugo-version }}
        extended: true

    - name: npm install, build, and test
      run: |
        export BUILD_PRODUCTION=Y
        npm install
        npm run build --if-present
        mkdir dist
        cp -rf site/public/ dist
        ls dist
  # Deployment job
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.GURUKULAMS_HOST }}
        username: ${{ secrets.GURUKULAMS_USER }}
        key: ${{ secrets.GURUKULAMS_KEY }}
        target: ${{ secrets.GURUKULAMS_MANDRAM_ROOT }}
        source: "dist"
        strip_components: 1
